### ISSUE TITLE
wandb

### ISSUE THREAD

**Issue by wj7486** [phil329/SDFlow#1]
Can you share your training logs. Thank you very much.

**Comment by phil329** [comment]
The training logs folder is very large (500MB) because of the image logged. You can just simply modify the configs of the wandb and run the training script to get the training logs. Here, I can share the screenshot of the losses plots.
![image](https://github.com/phil329/SDFlow/assets/59244383/0e8ba3ca-74ea-4f39-a941-6d40def495b2)

**Comment by wj7486** [comment]
Thank you for your reply！
